#pragma once

// Vial-specific settings
#define VIAL_KEYBOARD_UID {0x12, 0x34, 0x56, 0x78, 0x9A, 0xBC, 0xDE, 0xF0}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 5 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 0 }
#define DYNAMIC_KEYMAP_LAYER_COUNT 10
#define VIAL_INSECURE

// limits the number of LEDs to process in an animation per task run (increases keyboard responsiveness)
#define RGB_MATRIX_LED_PROCESS_LIMIT 15

// Define RGB layer colors
// Base layer (0) - RGB mode
// Enable all LED effects
// Ordinary Defines
#define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_BAND_SAT
#define ENABLE_RGB_MATRIX_BAND_VAL
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#define ENABLE_RGB_MATRIX_DUAL_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define ENABLE_RGB_MATRIX_FLOWER_BLOOMING
#define ENABLE_RGB_MATRIX_RAINDROPS
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define ENABLE_RGB_MATRIX_HUE_BREATHING
#define ENABLE_RGB_MATRIX_HUE_PENDULUM
#define ENABLE_RGB_MATRIX_HUE_WAVE
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#define ENABLE_RGB_MATRIX_PIXEL_FLOW
#define ENABLE_RGB_MATRIX_PIXEL_RAIN
#define ENABLE_RGB_MATRIX_STARLIGHT
#define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE
#define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT
#define ENABLE_RGB_MATRIX_RIVERFLOW
// Framebuffer Defines
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN
// Reactive Defines
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_SPLASH
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

// Layer 1 - Symbol layer - Purple
#define LAYER1_RGB_R 128
#define LAYER1_RGB_G 0
#define LAYER1_RGB_B 255

// Layer 2 - Number layer - Cyan
#define LAYER2_RGB_R 0
#define LAYER2_RGB_G 255
#define LAYER2_RGB_B 255

// Layer 3 - Green
#define LAYER3_RGB_R 0
#define LAYER3_RGB_G 255
#define LAYER3_RGB_B 0

// Layer 4 - Orange
#define LAYER4_RGB_R 255
#define LAYER4_RGB_G 128
#define LAYER4_RGB_B 0

// Layer 5 - Purple
#define LAYER5_RGB_R 128
#define LAYER5_RGB_G 0
#define LAYER5_RGB_B 255

// Layer 6 - Yellow
#define LAYER6_RGB_R 255
#define LAYER6_RGB_G 255
#define LAYER6_RGB_B 0

// Layer 7 - Blue
#define LAYER7_RGB_R 0
#define LAYER7_RGB_G 0
#define LAYER7_RGB_B 255

// Layer 8 - Red
#define LAYER8_RGB_R 255
#define LAYER8_RGB_G 0
#define LAYER8_RGB_B 0

// Layer 9 - Teal (Turquoise)
#define LAYER9_RGB_R 0
#define LAYER9_RGB_G 128
#define LAYER9_RGB_B 128

// Maintain compatibility with the keyboard's RGB Matrix settings
#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

// Disable RGB when USB is suspended to save power
#define RGB_DISABLE_WHEN_USB_SUSPENDED true

// Enable disabling of unmapped keys per layer
#define RGB_MATRIX_KEYRELEASES
#define RGB_MATRIX_TIMEOUT 0
#define RGB_MATRIX_DISABLE_KEYCODES

// Layer-specific lighting configuration
#define RGB_MATRIX_LAYER_INDICATORS
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 50
