RGB_MATRIX_ENABLE = yes
VIAL_ENABLE = yes
VIA_ENABLE = yes
LTO_ENABLE = yes
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
CAPS_WORD_ENABLE   = yes
REPEAT_KEY_ENABLE  = yes
COMBO_ENABLE = yes
ENCODER_MAP_ENABLE = yes

# Enable a more recent version of the RGB protocol
VIALRGB_ENABLE = yes
VIALRGB_CLIENT_SIDE_ENABLE = yes

# Disable RGB for unmapped keys in layers
RGB_MATRIX_KEYPRESSES = yes
RGB_DISABLE_WHEN_USB_SUSPENDED = yes
RGB_MATRIX_DISABLE_KEYCODES = yes
RGB_MATRIX_DISABLE_WHEN_NONE = yes